{% set name = "pytools" %}
{% set version = "2021.2.7" %}
{% set build_number = 0 %}
{% set sha256 = "0538f6fe7f00bf765ca5ab38518db48df72de818460006e54b0575accd24d9fb" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: {{ build_number }}
  noarch: python
  script: {{ PYTHON }} -m pip install . --no-deps -vv

requirements:
  host:
    - python >=3.6
    - setuptools
    - pip
  run:
    - python >=3.6
    - numpy
    - appdirs >=1.4.0

test:
  requires:
    - pytest
  imports:
    - {{ name }}
  source_files:
    - test
  commands:
    - cd test && python -m pytest


about:
  home: http://pypi.python.org/pypi/{{ name }}
  license: MIT
  license_file: LICENSE
  summary: A collection of tools for Python

  description: |
    Pytools is a big bag of things that are "missing" from the Python standard
    library. This is mainly a dependency of my other software packages, and is
    probably of little interest to you unless you use those. If you're curious
    nonetheless, here's what's on offer.

  dev_url: http://github.com/inducer/{{ name }}

extra:
  recipe-maintainers:
    - inducer
    - ocefpaf
