{% set name = "pytools" %}
{% set version = "2022.1.11" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 810173d62d5d6c391b137a6666be4a1616eae05df24d5ddbc0eada684a0180a2

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . --no-deps -vv

requirements:
  host:
    - python >=3.6
    - setuptools
    - pip
  run:
    - python >=3.6
    - platformdirs >=2.2.0
    - typing_extensions
    - appdirs >=1.4.0

test:
  requires:
    - pytest
    - pip
    - numpy >=1.6.0
  imports:
    - pytools
  source_files:
    - test
  commands:
    - pip check
    - cd test && python -m pytest

about:
  home: https://pypi.python.org/pypi/pytools
  license: MIT
  license_file: LICENSE
  summary: A collection of tools for Python

  description: |
    Pytools is a big bag of things that are "missing" from the Python standard
    library. This is mainly a dependency of my other software packages, and is
    probably of little interest to you unless you use those. If you're curious
    nonetheless, here's what's on offer.

  dev_url: https://github.com/inducer/pytools
  doc_url: https://documen.tician.de/pytools

extra:
  recipe-maintainers:
    - inducer
    - ocefpaf
    - matthiasdiener
