{% set name = "pytools" %}
{% set version = "2022.1.8" %}
{% set build_number = 0 %}
{% set sha256 = "1d793b4e01dd23704b62237ea5725d7ce772870fab7863f7903c41017bf5d79b" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: {{ build_number }}
  noarch: python
  script: {{ PYTHON }} -m pip install . --no-deps -vv

requirements:
  host:
    - python >=3.6
    - setuptools
    - pip
  run:
    - python >=3.6
    - typing_extensions
    - appdirs >=1.4.0

test:
  requires:
    - pytest
    - numpy
  imports:
    - {{ name }}
  source_files:
    - test
  commands:
    - cd test && python -m pytest


about:
  home: https://pypi.python.org/pypi/{{ name }}
  license: MIT
  license_file: LICENSE
  summary: A collection of tools for Python

  description: |
    Pytools is a big bag of things that are "missing" from the Python standard
    library. This is mainly a dependency of my other software packages, and is
    probably of little interest to you unless you use those. If you're curious
    nonetheless, here's what's on offer.

  dev_url: https://github.com/inducer/{{ name }}
  doc_url: https://documen.tician.de/{{ name }}

extra:
  recipe-maintainers:
    - inducer
    - ocefpaf
    - matthiasdiener
