{% set name = "pytools" %}
{% set version = "2016.2.4" %}
{% set sha256 = "4d033ae97e83129f21c4af56ca0df752bc3cd92c9f81669b72f0d3071620def5" %}

package:
    name: {{ name|lower }}
    version: {{ version }}

source:
    fn: {{ name }}-{{ version }}.tar.gz
    url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
    sha256: {{ sha256 }}

build:
    number: 0
    script: python setup.py install --single-version-externally-managed --record record.txt

requirements:
    build:
        - python
        - setuptools
        - six
    run:
        - python
        - numpy
        - decorator >=3.2.0
        - appdirs >=1.4.0
        - six

test:
    requires:
        - pytest
    imports:
        - {{ name }}
    commands:
         - cd $SRC_DIR/test && python -m pytest  # [unix]
         - cd %SRC_DIR%/test && python -m pytest  # [win]


about:
    home: http://pypi.python.org/pypi/{{ name }}
    license: MIT
    license_file: LICENSE
    summary: A collection of tools for Python

    description: |
        Pytools is a big bag of things that are “missing” from the Python standard
        library. This is mainly a dependency of my other software packages, and is
        probably of little interest to you unless you use those. If you’re curious
        nonetheless, here’s what’s on offer.

    dev_url: http://github.com/inducer/{{ name }}

extra:
    recipe-maintainers:
        - inducer
        - ocefpaf
