{% set name = "pytools" %}
{% set version = "2017.1.1" %}
{% set build_number = "0" %}
{% set sha256 = "9019dfaf00c8f955f1cdb831a72ce6d9741e20ca0501ca424b142339866c6465" %}

package:
    name: {{ name|lower }}
    version: {{ version }}

source:
    fn: {{ name }}-{{ version }}.tar.gz
    url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
    sha256: {{ sha256 }}

build:
    number: {{ build_number }}
    script: python setup.py install --single-version-externally-managed --record record.txt

requirements:
    build:
        - python
        - setuptools
        - six
    run:
        - python
        - numpy
        - decorator >=3.2.0
        - appdirs >=1.4.0
        - six

test:
    requires:
        - pytest
    imports:
        - {{ name }}
    source_files:
        - test
    commands:
        - cd test && python -m pytest


about:
    home: http://pypi.python.org/pypi/{{ name }}
    license: MIT
    license_file: LICENSE
    summary: A collection of tools for Python

    description: |
        Pytools is a big bag of things that are "missing" from the Python standard
        library. This is mainly a dependency of my other software packages, and is
        probably of little interest to you unless you use those. If you're curious
        nonetheless, here's what's on offer.

    dev_url: http://github.com/inducer/{{ name }}

extra:
    recipe-maintainers:
        - inducer
        - ocefpaf
