travis:
  secure:
    BINSTAR_TOKEN: aRhCcn+3zQziqtKy0HTJgaTgSV/prG7xJ8vGgOWXsCYfwSfUgHSyGivl4kKxLDLLz8BzPWmFB0l6MPPjoLFCPe+Icd8CJK/5j4lCRTrYpWP2FtBLWTh5CCYpdZmUOYLGCWBfpvjDrgA60F20JSpmj9FV5/CQ6G9JTzoU3M9KukxjImc0f6yZvk5o+s1HPFa9RBQxn9bbHXs23qUtgqpcKkKgjlYzBjBwCvWCmBEBCKKQT5SFZJxpesvxxjx1o27grg9bEd+5H2rIhGCANbByfkua7ZmS4SHACcrLDMEhdF/grdYTY8AOQ9PAA0y4ZVTXiXoAWNe509PqA19muZ9XMuXJgOxfVEtL0sGhCpda1mleVTBqy688izDQAL15vp3TOY+6aaqriBIhDkGTje/8pRzeEyFlCBrcQhuG+nFqMDvG7IA4MIsASErc0dyhd2FZdHzzGqRT9QT0XMkAEf/g8WG6hqCeKIHHcy7DIi+0buUjmY1s+6+lj3+eWmf/uOb+OIU0DgR1hOFUKLtUDiL6csfl6mt/i9GEMTpxPqi65jk+c0yU6LoeKR4w7eU/3+1SEnmKdw+ank7qv6gG2+JHcogfx+IXAUKZZB2pISmDAuxmoTy+6RF6WAQvGnKql2E9BfjpSA4GMG5YDxsj271xDBl3mvbSSz4ol2om74i8PHc=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
bot:
  automerge: true
conda_forge_output_validation: true
