travis:
  secure:
    BINSTAR_TOKEN: U/zNBfk1VKFc0p/2n6nGOb951G4MBma+12n8O7LSebROFJqaEwEXAsqjDBqqDJyCPe5Rpe9o4DKY9Aa0SbEuMziX3GFNrH79rm6f4/h5IxaDk4aEKiNLWsGCpx7EVbtLLMlGrHAEDcDn72P3tXTUvQKrbV6tFBALi5YmxZigr8AVN/j8V2qTBowenQnYxmvjSIwoqwuqUY5XGgxbLbVtzfYZF6Dka2ZADi3xklBFlfIaE1rZb1WOkU3LI8AkxBJJFeh1cNxWE9a2B1M0hlgcCehcZM9LbTSbbQGIhAiCwiY+ZrY50xBTJqyTZg75BWscW3tnAQHhJ64o2dMTfuOs8iWrrbREl7n1TJQXCV0ycmel/7lJbs5N/R/OMfrou6f0EsqVpViRVDNzQoRHNel8NKZSL7ocRcgfdFVKqVPMbG19ZY5Iup09DyM8q+usQ0M35RKnFEtN+NlVw2UTZikCNEm+f7Akj2wUe+wAam3//u2c2r6AslUHdV1M3/qdqslGBO9aK0shQZ8E1EHtxMz9VTOBo0JlBLYRVGoqDkak3wc5w8yhxZqKS4mio9o1A8g4bNc80U8K9tzQ9BgAvuEobf7B/hrmNahz+KjDzLIE0qthJHAr9AWwoTLZwuy8NN+sJPwEme+vx9Y3XeahbdavrMsQ0Iuc1Cum9HkmcXStA9M=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
